server:
  port: 9090
spring:
  profiles:
    active: local
---
spring:
  profiles:
    - local
  datasource:
    name: local
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-local
logging:
  level:
    org.springframework.web: ERROR
    com.example.mapping.example: ERROR
---
spring:
  profiles:
    - prod
  datasource:
    name: prod
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-prod
logging:
  level:
    org.springframework.web: ERROR
    com.example.mapping.example: warn
---
spring:
  profiles:
    - dev
  datasource:
    name: dev
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-dev
logging:
  level:
    org.springframework.web: ERROR
    com.example.mapping.example: info